# Generated by Django 3.2a1 on 2022-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='steamplatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plateform', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plateform')),
                ('about', models.CharField(blank=True, max_length=200, null=True, verbose_name='about')),
                ('website', models.URLField(max_length=150, verbose_name='website')),
            ],
            options={
                'db_table': 'steamplatform',
            },
        ),
    ]
