# Generated by Django 3.2a1 on 2022-12-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_movie_plateform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plateform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plateform_name', to='watchlist_app.steamplatform', verbose_name='plateform'),
        ),
    ]
